# sonic kvm image

SONIC_ROOTFS = rootfs.tar
$(SONIC_ROOTFS)_INSTALLS += $(SYSTEMD_SONIC_GENERATOR)
$(SONIC_ROOTFS)_MACHINE = vs
$(SONIC_ROOTFS)_IMAGE_TYPE = kvm
$(SONIC_ROOTFS)_DOCKERS = $(SONIC_INSTALL_DOCKER_IMAGES)
SONIC_INSTALLERS += $(SONIC_ROOTFS)
